# -*- coding: utf-8 -*-
"""A01794010 AnalisisP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rT2BQEqxb5ivTaoViAHj1Q5w5lWRnIdW
"""

import numpy as np
import pandas as pd

pip install pandas numpy

datos= pd.read_csv('/content/TC1.txt', index_col=0)
datos

nombres_columnas = ['TC1']

datos = pd.read_csv('/content/TC1.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')

print(descripcion)

moda = datos.mode().iloc[0]

varianza = datos.var()

mediana = datos.median()

print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)

descripcion.to_csv('resumen_estadistico.csv', index=False)

print("Resumen estadístico guardado en 'resumen_estadistico.txt'")

datos= pd.read_csv('/content/TC2.txt', index_col=0)
datos

nombres_columnas = ['TC2']

datos = pd.read_csv('/content/TC2.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')
print(descripcion)

moda = datos.mode().iloc[0]

varianza = datos.var()

mediana = datos.median()

print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)

descripcion.to_csv('resumen_estadistico2.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico2.txt'")

print("Resumen estadístico guardado en 'resumen_estadistico2.txt'")

datos= pd.read_csv('/content/TC3.txt', index_col=0)
datos

nombres_columnas = ['TC3']

datos = pd.read_csv('/content/TC3.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')
print(descripcion)

descripcion.to_csv('resumen_estadistico3.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico3.txt'")

datos= pd.read_csv('/content/TC4.txt', index_col=0)
datos

nombres_columnas = ['TC4']

datos = pd.read_csv('/content/TC4.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')
moda = datos.mode().iloc[0]
varianza = datos.var()
mediana = datos.median()

print(descripcion)
print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)

descripcion.to_csv('resumen_estadistico4.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico4.txt'")

datos = pd.read_csv('/content/TC5.txt', index_col=0, skiprows=154)
datos

nombres_columnas = ['TC5']

datos = pd.read_csv('/content/TC5.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')
print(descripcion)

moda = datos.mode().iloc[0]
varianza = datos.var()
mediana = datos.median()
print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)

descripcion.to_csv('resumen_estadistico5.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico5.txt'")

datos= pd.read_csv('/content/TC6.txt', index_col=0)
datos

nombres_columnas = ['TC6']

datos = pd.read_csv('/content/TC6.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')
moda = datos.mode().iloc[0]
varianza = datos.var()
mediana = datos.median()
print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)
print(descripcion)

descripcion.to_csv('resumen_estadistico6.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico6.txt'")

datos= pd.read_csv('/content/TC7.txt', index_col=0)
datos

nombres_columnas = ['TC7']

datos = pd.read_csv('/content/TC7.txt', delimiter='\t', names=nombres_columnas)

descripcion = datos.describe(include='all')

moda = datos.mode().iloc[0]
varianza = datos.var()
mediana = datos.median()
print("Estadísticas Descriptivas:")
print(descripcion)
print("\nModa:")
print(moda)
print("\nVarianza:")
print(varianza)
print("\nMediana:")
print(mediana)
print(descripcion)

descripcion.to_csv('resumen_estadistico7.csv', index=False)
print("Resumen estadístico guardado en 'resumen_estadistico7.txt'")