# -*- coding: utf-8 -*-
"""Alltest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDEUxYiN3MqHR40O7YgokB1hQa1JJlkY
"""

!python -m unittest /content/test_hotel.py
!python -m unittest /content/test_customer.py
!python -m unittest /content/test_customer.py