# -*- coding: utf-8 -*-
"""Coverage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xul0-1uBRTBwBbJFboE1m3yBSmq3weQa
"""

!pip install coverage

!coverage run -m unittest discover


!coverage report

!coverage report